### ISSUE TITLE
Max_bundles not working properly

### ISSUE THREAD

**Issue by likeadeckofcards** [Sammyjo20/Lasso#18]
I recently installed this package. It looks like the max_bundles setting is not working correctly. My setting is set to 5 bundles.

![Screen Shot 2020-09-10 at 6 11 41 PM](https://user-images.githubusercontent.com/6399755/92814435-19fc6400-f391-11ea-9660-75ef53f8d775.png)

**Comment by likeadeckofcards** [comment]
Actually this might be an issue where the process did not finish but uploaded the bundles but did not update the history.json file

**Comment by Sammyjo20** [comment]
Hey @likeadeckofcards, yeah I noticed this too yesterday - the bundles are getting deleted but not being removed from the history.json file. It’s on my list for things to fix but thank you for confirming the bug, I’ll get it sorted soon! ✌️

**Comment by likeadeckofcards** [comment]
I am closing this because the extra bundles that I was seeing were due to failed deployments, where the code threw an exception.

**Comment by Sammyjo20** [comment]
Great - I did look into this a little bit but couldn't find a bug. Glad it's working!
