### ISSUE TITLE
Add “—lasso-env” flag to manually specify the environment Lasso should upload to.

### ISSUE THREAD

**Issue by Sammyjo20** [Sammyjo20/Lasso#22]
Lasso's environment management system is pretty useful, but can be clunky if you are working locally. 

Adding a "--lasso-env=" flag to the publish command will upload your files to an exact environment.

**Comment by Sammyjo20** [comment]
I no longer feel this is needed.

**Comment by alexanderfrodeberg** [comment]
I would like this very much. I'm calling the `lasso:publish` from inside my own command as I need to do some other stuff as well. But now I need to silence the lasso command and set the `$filesystem->setLassoEnvironment($env);` myself; as I need the specified env for other things in my own command.
