### ISSUE TITLE
Write tests for Lasso

### ISSUE THREAD

**Issue by Sammyjo20** [Sammyjo20/Lasso#38]
Right, we need to get some tests in here!

I was wondering how specifically is the best way to test Lasso. Would the best way to test each individual component, e.g the backing up process?

**Comment by Sammyjo20** [comment]
Any suggestions for tests  are really appreciated!

**Comment by Sammyjo20** [comment]
Tests to write:

- [] Zip helper can zip files and folders up
- [] Zip helper can unzip files and checksum is correct
- [] Backup service can create a backup successfully
- [] Backup service can restore files and checksum matches
- [] Backup service can bring back sym-linked directories
- [] Versioning service can successfully append a new version
- [] Versioning service can successfully remove a version
- [] Archive service can successfully create
- [] Archive service can successfully extract
- [] File lister lists the correct files
- [] File lister excludes specified files
- [] File lister excludes specified directories
- [] Config validator throws exceptions at certain configurations
- [] Bundle integrity helpers creates and validates checksums correctly
- [] Lasso-bundle.json file is generated successfully
- [] Lasso-bundle.json can be read successfully
- [] Webhooks can send successfully
- [] Compiled assets can be uploaded to filesystem correctly

**Comment by Jhnbrn90** [comment]
Hi @Sammyjo20 

I've attempted to address the todo `Zip helper can zip files and folders up` in #48
