### ISSUE TITLE
Suggestion: Show filesystem name on lasso:publish

### ISSUE THREAD

**Issue by codepotato** [Sammyjo20/Lasso#4]
Love Lasso, and through usage I've found a couple of parts that I think could be nicer for the user. 

When running ```php artisan lasso:publish``` the progress simply says "filesystem". I think it would be nicer if it showed the name of the disk that you're uploading to, too! 

e.g. current setup: 

Preparing to publish assets to Filesystem.

Proposed change: 

Preparing to publish assets to "assets" Filesystem.

**Comment by Sammyjo20** [comment]
Thanks @codepotato, awesome addition! I'll merge this in for the next release. 👌
