### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by husonghua** [Sammyjo20/Lasso#40]
Hey, will Lasso add PHP 8 support soon?

**Comment by Sammyjo20** [comment]
Yes, this is something coming soon - but PHP 8 has barely been out a week.

**Comment by Sammyjo20** [comment]
Currently upgrading to PHP 8.0, everything works great, but I will be waiting for friendsofphp/php-cs-fixer to add full PHP 8 support ✅

**Comment by Sammyjo20** [comment]
PHP 8.0 support is ready, but I think it's important to write some tests before I roll out any more releases. Follow issue #34 for more!

**Comment by Sammyjo20** [comment]
Upgraded to PHP 8 early, as I feel it's more important to have this out there now and then build tests slater.
