### ISSUE TITLE
Breaks application after installation with cached config

### ISSUE THREAD

**Issue by srichter** [Sammyjo20/Lasso#43]
If your application's config is cached, installing Lasso will break the application (making the config cache unable to be cleared as well).

Since Lasso always registers into the container (#23) it will break when the Filesystem helper [attempts to instantiate](https://github.com/Sammyjo20/Lasso/blob/4ea2c36befedb1af955643ab6bfd20d82aaa45a8/src/Helpers/Filesystem.php#L34), due to `null` being passed to `setCloudDisk()` as that's what is returned from the `config()` helper due to no Lasso configuration being cached (it would break on `setPublicPath()` as well).

A temporary fix until #23 is resolved would be to just provide defaults for the config values here, like is done already for `lasso.storage.environment`.

**Comment by Sammyjo20** [comment]
Hey @srichter 

Thank you for your comment - I am aware of this issue. A workaround is to delete the 'config.php' cache file in '/bootstrap/cache'

I will definitely get this sorted though so thank you for raising it here!

**Comment by Sammyjo20** [comment]
I have fixed this in #45 ! Thanks for reporting @srichter
