### ISSUE TITLE
Manage Bundles During Push

### ISSUE THREAD

**Issue by Hornet-Wing** [Sammyjo20/Lasso#56]
Hi Sam,

Firstly, thanks for this package!

I'd like to ask what's the reasoning for managing bundles during pull rather than during push?

The reason I ask is because if history and bundles were managed during push I could distribute read-only access credentials to the majority of users, which would allow them to pull, and manage builds and pushing in the CI pipeline. Currently, if read-only credentials are used the `PullJob` fails at the ` VersioningService::appendNewVersion()` step so it's not possible.

**Comment by Sammyjo20** [comment]
Hey @Hornet-Wing 

That's a very good point. I think if the publish command was used to manage the versions it would be a lot better, the pull command could just read the file and then there's no history written. 

This also relates to #44. 

I can't promise anything urgent but after looking at the code again I feel Lasso needs a bit of a refresh and a brand new version.

**Comment by Hornet-Wing** [comment]
Yes, you're right it's the same issue. Thanks for taking a look!
