### ISSUE TITLE
Error publishing assets when using with Laravel Sail

### ISSUE THREAD

**Issue by 77media-creations** [Sammyjo20/Lasso#58]
Hello,

I ran into an error when using `sail artisan lasso:publish` with Laravel Sail. However, I was able to publish the assets successfully without using Sail `php artisan lasso:publish` on my laptop.

Wondering if there are any configurations to be added/changed when using with Sail?

Lasso version: `^1.2`
Laravel: `8.70.1`
PHP: `7.4.2`

<img width="489" alt="Screen Shot 2022-01-25 at 12 41 31 am" src="https://user-images.githubusercontent.com/51688338/150793911-9dc504e3-c9e6-4a79-af8e-5834c436084f.png">

**Comment by Sammyjo20** [comment]
Hey @77media-creations,

Have you tried changing the command in config/lasso.php to `sail npm run production` since that will then run inside the Docker container?
