### ISSUE TITLE
FileExistsException when Uploading asset bundle to "s3" filesystem

### ISSUE THREAD

**Issue by dovid** [Sammyjo20/Lasso#62]
I have a feeling the recent update to 2.0.2 is causing the below error during publishing to s3. I'm on Laravel 8.

```
Uploading asset bundle to "s3" filesystem...

Illuminate\Contracts\Filesystem\FileExistsException 

File already exists at path: [path to file]/lasso-bundle.json
```

I rolled back to 2.0.1 and the error is gone.

**Comment by Sammyjo20** [comment]
Ah... Okay, I thought that maybe this could happen with writeStream, apologies I will try and get this sorted ASAP.

**Comment by Sammyjo20** [comment]
This should be fixed now, please upgrade to the latest version for Laravel 8 - v2.0.3

**Comment by dovid** [comment]
I can confirm it's fixed.

Thank You!
