### ISSUE TITLE
Suggestion: Exclude Wildcard Filename

### ISSUE THREAD

**Issue by patrickquijano** [Sammyjo20/Lasso#64]
Kudos to this package! This is really an awesome tool for Laravel.

Is it possible to exclude filenames using wildcards? I tried using wildcards but it does not work.
![image](https://user-images.githubusercontent.com/6316829/162374576-42ec1238-d3ff-4b2e-a182-30b2ac849204.png)

Thanks!

**Comment by Sammyjo20** [comment]
Hey @patrickquijano thank you for your kind comment, I won't be implementing this for now but I would be happy to accept a PR in the future for this.
