### ISSUE TITLE
Write fails silently in Laravel 9

### ISSUE THREAD

**Issue by cwilsn** [Sammyjo20/Lasso#66]
Example: `export AWS_SECRET_ACCESS_KEY=invalid-key && php artisan lasso:publish`

Output makes you think all is good when it is not.

#65 should resolve it.

**Comment by cwilsn** [comment]
Until this is merged you can add `'throw' => true,` to your filesystems config for your assets (lasso) driver

**Comment by Sammyjo20** [comment]
Released in v3.0.1 🥳 Thanks @pusherman
